# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F8k3agxrgmQt_JFj_MdDcYZjaA9W9ITH
"""

import os
os.chdir('/content/drive/MyDrive')

!git clone https://github.com/rohithrede/Boundary-Detection

os.chdir('/content/drive/MyDrive/Boundary-Detection')

# Commented out IPython magic to ensure Python compatibility.
 #testing the trained model
 
#  %run test.py test/26.png --output_mask=test/output_mask.png --output_prediction=test/output_pred.png --model=./pretrained/model_final.pt

